# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-15 08:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aname', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Eassy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etitle', models.CharField(max_length=10)),
                ('etext', models.CharField(max_length=50)),
                ('ecount', models.IntegerField(default=0)),
                ('eauthor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.Author')),
            ],
        ),
    ]
