# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-15 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_author_eassy'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='aage',
            field=models.IntegerField(default=18),
        ),
        migrations.AddField(
            model_name='author',
            name='asex',
            field=models.BooleanField(default=0),
        ),
    ]
