# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-17 01:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_auto_20171015_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='bcount',
            field=models.IntegerField(default=0),
        ),
    ]
